# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  OPENSVC_CI_EXTRA_TIME_OSVCD_STARTUP: "15"
  PYTHONPATH: "opensvc"

stages:
  - "test"

.test:
  script:
    - id
    - apk add build-base sudo git procps
    - python -V
    - ln -s /bin/touch /usr/bin/touch
    - pip install -r test-requirements.txt codecov
    - pytest --cov -m "ci"
    - pylint -E opensvc/*py opensvc/commands opensvc/core opensvc/daemon opensvc/drivers opensvc/utilities
    - codecov

test-2.7:
  extends: ".test"
  stage: "test"
  image: "python:2.7.17-alpine3.11"

test-3.6:
  extends: ".test"
  stage: "test"
  image: "python:3.6.10-alpine3.11"
