env:
  - OPENSVC_CI_EXTRA_TIME_OSVCD_STARTUP=25
sudo: true
language: python
cache: pip
branches:
  only:
  - master
  - b2.0
  - b2.1
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.6'
before_install:
  - sudo apt-get update
  - sudo apt-get -y install procps
install:
- pip install -r test-requirements.txt
script:
- sudo $(which pytest) --cov -m "ci"
- PYTHONPATH=opensvc pylint -E opensvc/*py opensvc/commands opensvc/core opensvc/daemon opensvc/drivers opensvc/utilities
after_success:
- pip install codecov
- codecov
notifications:
  slack:
    secure: pMUKCIMIx8DPpEKfDRtJqv7S3/TCVNMRwKBOOcpbkGf6lRGlgnbBPgtUYAIL8Bi2vwY5Bj+I7B08VNYz21MJ6ZwhQ7LoeJJtxnuTuhigHlKeC6fl2Olmkk1yD/6tjOQL83uiOomY8XRmwws51X1gpUVIA4jz8nwMcr5qsE5NjdyOoUFs6C/Pza8Cz2PyL9TRIxToHm5eBldyntxgM2+fzFBGEizxLLH79+sHdvO6ApBr8zaIjtRYojpFzbrtfj5CV6flnjxTMkiKAhvSIBcIBeijKXzfeJTXRDylwX2i2UO9rUQDNjucKciFCG2s90KiiC0D1rlxkD5dii0yvCzzSwqZ8K5cRb65+T7PyOHh5sHSXIa6cOp+nsqgcJbdHCoAqc/6MDGrhkeRxT+teT0K8M35DYneCjZ5ZAxv1HBxL1HU8BWwhgqktOMNnqvU7wOoK/4Ir+Vv3mGzMSeM7hHG3ETT06vvHOXWniEImmfFOy85JenbH3As54pB6ysnOc4MJkZbCUhkb9irTH/ifwyDeYhiqfuv8IyDCdasbfKb9m5nuIt7bB1xNiFP48rKh2n7Ogr8uPrwCqTqxNFQAJ182E7Hr1wT3YkH2WxyCJyHE/qnkBTpS1dQqtQXRmpYQyD9/PGXr9EiNm/YlN8PjdJZ+uy1+7EfPg3sV4ZMbJqVopo=
